config/routes.rb
Rails.application.routes.draw do
  # get "/books", to: "books#index"
  # post "/books", to: "books#create"
  # get "/books/new", to: "books#new", as: "new_book"
  # get "/books/:id/edit", to: "books#edit", as: "edit_book"
  # get "/books/:id", to: "books#show", as: "book"
  # patch "/books/:id", to: "books#update"
  # delete "/books/:id", to: "books#destroy"
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :year, presence: true
  validates :month, presence: true
  validates :inout, presence: true
  validates :category, presence: true
  validates :amount, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [ :show, :edit, :update, :destroy ]

  def index
    @books = Book.all
    @books = @books.where(year: params[:year]) if params[:year].present?
    @books = @books.where(month: params[:month]) if params[:month].present?
  end

  def show
  end

  def new
    @book = Book.new
  end

  def create
    # book_params = params.require(:book).permit(:year, :month, :inout, :category, :amount)
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "家計簿に#{@book.year}年#{@book.month}月#{@book.category}を登録しました"
    redirect_to books_path
    else
      flash.now[:alert] = "登録に失敗しました"
      render :new
    end
  end

  def edit
  end

  def update
    # book_params = params.require(:book).permit(:year, :month, :inout, :category, :amount)
    if @book.update(book_params)
      flash[:notice] = "更新が完了しました"
      redirect_to book_path
    else
      flash.now[:alert] = "更新に失敗しました"
      render :edit
    end
  end

  def destroy
    @book.destroy
    flash[:notice] = "削除されました"
    redirect_to books_path
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:year, :month, :inout, :category, :amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<h1>家計簿<%= type %></h1>

<%= form_with model: book, local: true, method: method do |f| %>
  <div class="form-group">
    <label>年度</label>
    <%= f.number_field :year, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>月</label>
    <%= f.number_field :month, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>区分</label>
    <%= f.select :inout, [["収入", 1],["支出", 2]], {}, {class: "form-control"} %>
  </div>

  <div class="form-group">
    <label>科目</label>
    <%= f.text_field :category, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>金額</label>
    <%= f.number_field :amount, class: "form-control" %>
  </div>

  <%= f.submit submit_type, class: "btn btn-primary" %>
  <%= link_to "一覧に戻る", books_path, class: "btn btn-secondary" %>

<% end %>

app/views/books/edit.html.erb
<%= render partial: "form", locals: { type: "編集", submit_type: "更新", book: @book, method: "patch" } %>

app/views/books/index.html.erb
<h1>家計簿</h1>
<div class="card">
  <div class="card-body">
    <%= form_with method: "get", local: true do |f| %>
      <div class="form-row">
        <div class="col">
          <%= f.number_field "year", placeholder: "年度を入力", class: "form-control" %>
        </div>
        <div class="col">
          <%= f.number_field "month", placeholder: "対象月を入力", class: "form-control" %>
        </div>
        <div class="col">
          <%= f.submit "検索", class:"btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= link_to "新規登録", new_book_path, class: "btn btn-success" %>
<table class="table table-striped">
  <tr>
    <th>年月</th>
    <th>区分</th>
    <th>科目</th>
    <th>金額</th>
  </tr>
  <% sum = 0 %>
  <% expenditure_sum = 0 %>
  <% income_sum = 0 %>
  <% @books.each do|book| %>
    <tr>
      <td><%= book.year %>年<%= book.month %>月</td>
      <% if book.inout == 1 %>
        <td>収入</td>
      <% else %>
        <td>支出</td>
      <% end %>
      <td><%=book.category%></td>
      <td><%=book.amount%>万円</td>
      <td>
        <%= link_to "詳細", book_path(book), class: "btn btn-info" %>
        <%= link_to "編集", edit_book_path(book), class: "btn btn-warning" %>
        <%= link_to "削除", book_path(book), method: "delete", data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
      </td>
    </tr>
    <% if book.inout == 1 %>
      <% sum += book.amount %>
    <% else %>
      <% sum -= book.amount %>
    <% end %>
    <% if book.inout == 1 %>
      <% expenditure_sum += book.amount %>
    <% end %>
    <% if book.inout == 2 %>
      <% income_sum += book.amount %>
    <% end %>
  <% end %>
  <tr>
    <td>収入合計</td>
    <td><%= expenditure_sum %>万円</td>
    <td>支出合計</td>
    <td><%= income_sum %>万円</td>
    <td>合計</td>
    <td><%= sum %>万円</td>
    </tr>
</table>

app/views/books/new.html.erb
<%= render partial: "form", locals: { type: "新規登録", submit_type: "登録", book: @book, method: nil } %>

app/views/books/show.html.erb
<h1>家計簿詳細</h1>
<table class="table table-striped">
  <tr>
    <th>年月</th>
    <td><%= @book.year %>年<%= @book.month %>月</td>
  </tr>
  <tr>
    <th>区分</th>
    <td><%= @book.inout %></td>
  </tr>
  <tr>
    <th>科目</th>
    <td><%= @book.category %></td>
  </tr>
  <tr>
    <th>金額</th>
    <td><%= @book.amount %>万円</td>
  </tr>
</table>
<%= link_to "一覧画面に戻る", books_path, class: "btn btn-secondary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kakeibo2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" integrity="sha384VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
        <% if flash[:notice] %>
          <div class="alert alert-success" role="alert">
            <%= flash[:notice] %>
          </div>
        <% end %>
        <% if flash[:alert] %>
          <div class="alert alert-danger" role="alert">
            <%= flash[:alert] %>
          </div>
        <% end %>
        <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery3.5.1.slim.min.js" integrity="sha384DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha3849/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/js/bootstrap.min.js" integrity="sha384XEerZL0cuoUbHE4nZReLT7nx9gQrQreJekYhJD9WNWhH8nEW+0c5qq7aIo2Wl30J" crossorigin="anonymous"></script>
  </body>
</html>